language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover
  - coverage erase
  - coverage run -m pytest && coverage html
#  - pylint --output-format=text main.py --disable=C0103

after_success:
  - codecov